CREATE TABLE  "LOANS" 
   (	"LOANID" NUMBER(12,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(255), 
	"AMOUNT" NUMBER(21,0), 
	"INTERESTRATE" NUMBER(3,0), 
	"PAYMENTCOUNT" NUMBER(5,0), 
	"PAYMENTFREQUENCY" NUMBER(1,0), 
	"FIRSTPAYMENTDATE" NUMBER(13,0), 
	"CREATEDATE" NUMBER(13,0), 
	"USERID" NUMBER(12,0), 
	 CONSTRAINT "LOANS_PK" PRIMARY KEY ("LOANID") ENABLE
   ) ;
   
CREATE TABLE  "PAYMENTS" 
   (	"PAYMENTID" NUMBER(12,0) NOT NULL ENABLE, 
	"LOANID" NUMBER(12, 0) NOT NULL, 
	"AMOUNT" NUMBER(21,0), 
	"PAYDATE" NUMBER(13,0), 
	"CREATEDATE" NUMBER(13,0), 
	"USERID" NUMBER(12,0), 
	"ISPAID" NUMBER(1,0) NOT NULL,
	 CONSTRAINT "PAYMENTS_PK" PRIMARY KEY ("PAYMENTID") ENABLE
   ) ;